set_property SRC_FILE_INFO {cfile:D:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.runs/synth_1/.Xil/Vivado-11200-DESKTOP-RONFFCB/dcp/Inst_mem_in_context.xdc rfile:../dcp/Inst_mem_in_context.xdc id:1 order:EARLY scoped_inst:u_ins_mem} [current_design]
set_property SRC_FILE_INFO {cfile:D:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.runs/synth_1/.Xil/Vivado-11200-DESKTOP-RONFFCB/dcp_2/data_mem_in_context.xdc rfile:../dcp_2/data_mem_in_context.xdc id:2 order:EARLY scoped_inst:u_data_mem} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_ins_mem/clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ins_mem]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_data_mem/clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_data_mem]
