# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.srcs/sources_1/ip/Inst_mem/Inst_mem.xci
# IP: The module: 'Inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.srcs/sources_1/ip/Inst_mem/Inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.srcs/sources_1/ip/Inst_mem/Inst_mem.xci
# IP: The module: 'Inst_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/study/COD/lab/lab7_cpu_pipeline/lab7/lab7.srcs/sources_1/ip/Inst_mem/Inst_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Inst_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
